add_test([=[AsciiArtTest.DummyTest]=]  /Users/lucyhadden/COSC345/build-coverage/runTests [==[--gtest_filter=AsciiArtTest.DummyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AsciiArtTest.DummyTest]=]  PROPERTIES WORKING_DIRECTORY /Users/lucyhadden/COSC345/build-coverage SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EndScreenTest.DummyTest]=]  /Users/lucyhadden/COSC345/build-coverage/runTests [==[--gtest_filter=EndScreenTest.DummyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EndScreenTest.DummyTest]=]  PROPERTIES WORKING_DIRECTORY /Users/lucyhadden/COSC345/build-coverage SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InteractionsTest.DummyTest]=]  /Users/lucyhadden/COSC345/build-coverage/runTests [==[--gtest_filter=InteractionsTest.DummyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InteractionsTest.DummyTest]=]  PROPERTIES WORKING_DIRECTORY /Users/lucyhadden/COSC345/build-coverage SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ItemTest.DummyTest]=]  /Users/lucyhadden/COSC345/build-coverage/runTests [==[--gtest_filter=ItemTest.DummyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ItemTest.DummyTest]=]  PROPERTIES WORKING_DIRECTORY /Users/lucyhadden/COSC345/build-coverage SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PlayerTest.DummyTest]=]  /Users/lucyhadden/COSC345/build-coverage/runTests [==[--gtest_filter=PlayerTest.DummyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PlayerTest.DummyTest]=]  PROPERTIES WORKING_DIRECTORY /Users/lucyhadden/COSC345/build-coverage SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_TESTS AsciiArtTest.DummyTest EndScreenTest.DummyTest InteractionsTest.DummyTest ItemTest.DummyTest PlayerTest.DummyTest)
